language: d

sudo: required
dist: trusty

d:
  - ldc
  - dmd
  - dmd-2.074.0
  - dmd-2.073.2
  - dmd-2.072.2
  - dmd-2.071.2
  - dmd-2.070.2
  - ldc-1.2.0 # eq to dmd v2.072.2
  - ldc-1.1.1 # eq to dmd v2.071.2
  - ldc-1.0.0 # eq to dmd v2.070.2
  - gdc

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install sqlite && brew link --force sqlite; fi"

os:
 - linux
 - osx

script:
  - dub build --config=SQLite --compiler=${DC}
  - cd hdtest && dub --config=SQLite --compiler=${DC}

addons:
  apt:
    packages: [ libsqlite3-dev ]

matrix:
  allow_failures:
    - d: gdc
